var configurationExamples = {
    Knotweed:
        {
            upwardTendency: 0.12,
            branchStrengthAfterTrunkDeath: 0.2,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 40,
            loss: 0.02,
            baseLoss: 0.0009,
            minSleep: 10,
            branchLoss: 0.6,
            mainLoss: 0.7,
            speed: 0.25,
            newBranch: 0.55,
            leaves: 0.85,
            leafSize: 0.7,
            downyLeaves: true,
            downyCoefficient: 3.5,
            treeColor: 'rgba(230, 93, 80, 1)',
            leafColor: 'rgba(0,255,0,1)',
            fastMode: false,
            fadeOut: false,
            fadeAmount: 0.05,
            autoSpawn: false,
            spawnInterval: 250,
            fadeInterval: 250,
            initialWidth: 5,
            indicateNewBranch: true,
            fitScreen: false,
            bgColor: [0, 0, 0]
        },
    RedKnotweed: {
        upwardTendency: 0.12,
        branchStrengthAfterTrunkDeath: 0.2,
        heightBeforeBranchingBasedOnWidth: 0,
        heightBeforeBranchingBasedOnHeight: 59,
        lifeBeforeLeafing: 20,
        loss: 0.02,
        baseLoss: 0.0009,
        minSleep: 10,
        branchLoss: 0.6,
        mainLoss: 0.7,
        speed: 0.25,
        newBranch: 0.55,
        leaves: 0.85,
        leafSize: 0.7,
        downyLeaves: true,
        downyCoefficient: 3.5,
        treeColor: 'rgba(230, 200, 200, 1)',
        leafColor: 'rgba(255,25,0,1)',
        fastMode: false,
        fadeOut: false,
        fadeAmount: 0.05,
        autoSpawn: false,
        spawnInterval: 250,
        fadeInterval: 250,
        initialWidth: 5,
        indicateNewBranch: true,
        fitScreen: false,
        bgColor: [0, 0, 0]
    },
    Mistyweed:
        {
            upwardTendency: 0.5,
            branchStrengthAfterTrunkDeath: 0.2,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 20,
            loss: 0.02,
            baseLoss: 0.0009,
            minSleep: 10,
            branchLoss: 0.6,
            mainLoss: 0.7,
            speed: 0.25,
            newBranch: 0.55,
            leaves: 0.85,
            leafSize: 0.7,
            downyLeaves: true,
            downyCoefficient: 3.5,
            treeColor: 'rgba(100, 22,20, 1)',
            leafColor: 'rgba(25,255,233,1)',
            fastMode: false,
            fadeOut: false,
            fadeAmount: 0.05,
            autoSpawn: false,
            spawnInterval: 250,
            fadeInterval: 250,
            initialWidth: 5,
            indicateNewBranch: true,
            fitScreen: false,
            bgColor: [0, 0, 0]
        },
    Swampweed:
        {
            upwardTendency: 0.12,
            branchStrengthAfterTrunkDeath: 0.25,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 45,
            loss: 0.01,
            baseLoss: 0.09,
            minSleep: 10,
            branchLoss: 0.8,
            mainLoss: 0.7,
            speed: 0.25,
            newBranch: 0.25,
            leaves: 0.65,
            leafSize: 1.4,
            downyLeaves: true,
            downyCoefficient: 3.5,
            treeColor: 'rgba(230, 10, 10, 1)',
            leafColor: 'rgba(100,100,0,1)',
            fastMode: false,
            fadeOut: false,
            fadeAmount: 0.05,
            autoSpawn: false,
            spawnInterval: 250,
            fadeInterval: 250,
            initialWidth: 5,
            indicateNewBranch: true,
            fitScreen: false,
            bgColor: [0, 0, 0]
        },
    CherryBlossom:
        {
            upwardTendency: 0.1,
            branchStrengthAfterTrunkDeath: 0.2,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 36,
            loss: 0.02,
            baseLoss: 0.009,
            minSleep: 10,
            branchLoss: 0.9,
            mainLoss: 0.7,
            speed: 0.55,
            newBranch: 0.55,
            leaves: 0.25,
            leafSize: 0.7,
            downyLeaves: false,
            downyCoefficient: 3.5,
            maxLife: 90,
            treeColor: 'rgba(80, 30, 8, 1)',
            leafColor: 'rgba(230,100, 190,1)',
            initialWidth: 5,
        },
    DesertWeed:
        {
            upwardTendency: 0.07,
            branchStrengthAfterTrunkDeath: 0.2,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 40,
            loss: 0.02,
            baseLoss: 0.0001,
            minSleep: 10,
            branchLoss: 0.9,
            mainLoss: 0.7,
            speed: 0.25,
            newBranch: 0.55,
            leaves: 0.98,
            leafSize: 0.9,
            downyLeaves: true,
            downyCoefficient: 1.5,
            treeColor: 'rgba(200, 93, 80, 1)',
            leafColor: 'rgba(200,255,2,1)',
            initialWidth: 7,
        },
    Bamboo:
        {
            upwardTendency: 0.12,
            branchStrengthAfterTrunkDeath: 0.2,
            heightBeforeBranchingBasedOnWidth: 0,
            heightBeforeBranchingBasedOnHeight: 59,
            lifeBeforeLeafing: 40,
            loss: 0.02,
            baseLoss: 0.0119,
            minSleep: 10,
            branchLoss: 0.2,
            mainLoss: 0.97,
            speed: 0.25,
            newBranch: 0.80,
            leaves: 0.45,
            leafSize: 0.7,
            downyLeaves: true,
            downyCoefficient: 3.5,
            maxLife: 70,
            treeColor: 'rgba(100, 193, 80, 1)',
            leafColor: 'rgba(0,255,0,1)',
            initialWidth: 5,
        },
}